server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:midas;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    consumer:
      group-id: midas-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      fail-fast: false

app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:${spring.kafka.bootstrap-servers:localhost:9092}}
    topic:
      transactions: midas-transactions
    listeners:
      auto-startup: true

incentive:
  base-url: http://localhost:8081

general:
  kafka-topic: ${APP_GENERAL_KAFKA_TOPIC:midas-transactions}
